# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2  
      # Runs a single command using the runners shell
      - name: terraform-lint-with-diff
        uses: alexnorell/terraform-lint@v1.0.0
